import {QuestionBank} from "./question.ts";

export const questionBanks: QuestionBank[] = [
    {
        id: 1,
        name: "General Knowledge",
        questions: [
            { id: 1, category: "General Knowledge", question: "What is the tallest building in the world?", options: ["Shanghai Tower", "Burj Khalifa", "Empire State Building", "Taipei 101"], correctAnswer: 1 },
            { id: 2, category: "General Knowledge", question: "What is the largest desert in the world?", options: ["Sahara Desert", "Gobi Desert", "Antarctic Desert", "Kalahari Desert"], correctAnswer: 2 },
            { id: 3, category: "General Knowledge", question: "Who wrote the national anthem of the USA?", options: ["Francis Scott Key", "Mark Twain", "George Washington", "Abraham Lincoln"], correctAnswer: 0 },
            { id: 4, category: "General Knowledge", question: "Which is the smallest country in the world?", options: ["Monaco", "Malta", "Vatican City", "San Marino"], correctAnswer: 2 },
            { id: 5, category: "General Knowledge", question: "What is the capital of Canada?", options: ["Toronto", "Ottawa", "Vancouver", "Montreal"], correctAnswer: 1 },
            { id: 6, category: "General Knowledge", question: "What is the largest planet in our solar system?", options: ["Earth", "Mars", "Jupiter", "Saturn"], correctAnswer: 2 },
            { id: 7, category: "General Knowledge", question: "Which is the only continent with no active volcanoes?", options: ["Australia", "Africa", "Antarctica", "Europe"], correctAnswer: 0 },
            { id: 8, category: "General Knowledge", question: "What is the official language of Brazil?", options: ["Spanish", "Portuguese", "French", "English"], correctAnswer: 1 },
            { id: 9, category: "General Knowledge", question: "Which organ in the human body controls the nervous system?", options: ["Heart", "Liver", "Brain", "Kidney"], correctAnswer: 2 },
            { id: 10, category: "General Knowledge", question: "What is the currency of Japan?", options: ["Yuan", "Yen", "Won", "Dollar"], correctAnswer: 1 },
        ],
    },
    {
        id: 2,
        name: "Science",
        questions: [
            { id: 1, category: "Science", question: "What is the speed of light?", options: ["300,000 km/s", "150,000 km/s", "1,000,000 km/s", "500,000 km/s"], correctAnswer: 0 },
            { id: 2, category: "Science", question: "What is the main gas found in the Earth's atmosphere?", options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], correctAnswer: 1 },
            { id: 3, category: "Science", question: "What is the chemical symbol for water?", options: ["H2O", "CO2", "O2", "H2O2"], correctAnswer: 0 },
            { id: 4, category: "Science", question: "Which organelle is known as the powerhouse of the cell?", options: ["Nucleus", "Mitochondria", "Ribosome", "Golgi apparatus"], correctAnswer: 1 },
            { id: 5, category: "Science", question: "What gas do plants use for photosynthesis?", options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Methane"], correctAnswer: 2 },
            { id: 6, category: "Science", question: "What planet is known as the Red Planet?", options: ["Mars", "Venus", "Jupiter", "Saturn"], correctAnswer: 0 },
            { id: 7, category: "Science", question: "What is the largest organ in the human body?", options: ["Heart", "Skin", "Liver", "Brain"], correctAnswer: 1 },
            { id: 8, category: "Science", question: "What is the atomic number of hydrogen?", options: ["1", "2", "8", "10"], correctAnswer: 0 },
            { id: 9, category: "Science", question: "What is the pH level of pure water?", options: ["5", "7", "9", "11"], correctAnswer: 1 },
            { id: 10, category: "Science", question: "What is the name of our galaxy?", options: ["Andromeda", "Milky Way", "Sombrero", "Whirlpool"], correctAnswer: 1 },
        ],
    },
    {
        id: 3,
        name: "History",
        questions: [
            { id: 1, category: "History", question: "Who was the first President of the United States?", options: ["George Washington", "Thomas Jefferson", "Abraham Lincoln", "John Adams"], correctAnswer: 0 },
            { id: 2, category: "History", question: "In which year did World War II end?", options: ["1940", "1942", "1945", "1950"], correctAnswer: 2 },
            { id: 3, category: "History", question: "Who discovered America?", options: ["Christopher Columbus", "Marco Polo", "Ferdinand Magellan", "James Cook"], correctAnswer: 0 },
            { id: 4, category: "History", question: "What empire was ruled by Julius Caesar?", options: ["Roman Empire", "Ottoman Empire", "Byzantine Empire", "British Empire"], correctAnswer: 0 },
            { id: 5, category: "History", question: "What year did the Titanic sink?", options: ["1912", "1914", "1916", "1920"], correctAnswer: 0 },
            { id: 6, category: "History", question: "Who was the first woman to win a Nobel Prize?", options: ["Marie Curie", "Rosalind Franklin", "Ada Lovelace", "Florence Nightingale"], correctAnswer: 0 },
            { id: 7, category: "History", question: "What was the name of the first human to walk on the Moon?", options: ["Yuri Gagarin", "Neil Armstrong", "Buzz Aldrin", "Michael Collins"], correctAnswer: 1 },
            { id: 8, category: "History", question: "Which war was fought between the North and South regions in the USA?", options: ["World War I", "The Civil War", "Vietnam War", "Cold War"], correctAnswer: 1 },
            { id: 9, category: "History", question: "What was the name of the ship used by Charles Darwin?", options: ["HMS Victory", "HMS Beagle", "Santa Maria", "Mayflower"], correctAnswer: 1 },
            { id: 10, category: "History", question: "In what year did the Berlin Wall fall?", options: ["1985", "1987", "1989", "1991"], correctAnswer: 2 },
        ],
    },
    {
        id: 4,
        name: "Geography",
        questions: [
            { id: 1, category: "Geography", question: "What is the capital of France?", options: ["London", "Berlin", "Paris", "Madrid"], correctAnswer: 2 },
            { id: 2, category: "Geography", question: "What is the largest ocean on Earth?", options: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"], correctAnswer: 3 },
            { id: 3, category: "Geography", question: "Which country is the largest by land area?", options: ["USA", "Canada", "Russia", "China"], correctAnswer: 2 },
            { id: 4, category: "Geography", question: "Which river is the longest in the world?", options: ["Amazon River", "Nile River", "Yangtze River", "Mississippi River"], correctAnswer: 1 },
            { id: 5, category: "Geography", question: "What is the capital of Australia?", options: ["Sydney", "Melbourne", "Canberra", "Perth"], correctAnswer: 2 },
            { id: 6, category: "Geography", question: "Which country is home to the Great Barrier Reef?", options: ["USA", "Australia", "Brazil", "South Africa"], correctAnswer: 1 },
            { id: 7, category: "Geography", question: "Which country has the most volcanoes?", options: ["Japan", "Indonesia", "USA", "Italy"], correctAnswer: 1 },
            { id: 8, category: "Geography", question: "Which city is known as the Big Apple?", options: ["Los Angeles", "New York", "Chicago", "San Francisco"], correctAnswer: 1 },
            { id: 9, category: "Geography", question: "Which continent is the Sahara Desert located on?", options: ["Asia", "Africa", "North America", "Australia"], correctAnswer: 1 },
            { id: 10, category: "Geography", question: "What is the largest island in the world?", options: ["Greenland", "Australia", "New Guinea", "Borneo"], correctAnswer: 0 },
        ],
    },
    {
        id: 5,
        name: "Entertainment",
        questions: [
            { id: 1, category: "Entertainment", question: "Which movie won the Academy Award for Best Picture in 1994?", options: ["Forrest Gump", "The Shawshank Redemption", "Titanic", "Pulp Fiction"], correctAnswer: 0 },
            { id: 2, category: "Entertainment", question: "Who is known as the 'King of Pop'?", options: ["Michael Jackson", "Elvis Presley", "Prince", "Freddie Mercury"], correctAnswer: 0 },
            { id: 3, category: "Entertainment", question: "What is the name of the fictional wizarding school in the Harry Potter series?", options: ["Hogwarts", "Durmstrang", "Beauxbatons", "Ilvermorny"], correctAnswer: 0 },
            { id: 4, category: "Entertainment", question: "Which actor portrayed the character of Jack Sparrow in 'Pirates of the Caribbean'?", options: ["Johnny Depp", "Brad Pitt", "Leonardo DiCaprio", "Tom Cruise"], correctAnswer: 0 },
            { id: 5, category: "Entertainment", question: "Who directed the movie 'Avatar'?", options: ["James Cameron", "Steven Spielberg", "Christopher Nolan", "George Lucas"], correctAnswer: 0 },
            { id: 6, category: "Entertainment", question: "What is the name of the fictional city in the Marvel Cinematic Universe where Black Panther resides?", options: ["Wakanda", "Genovia", "Gotham", "Metropolis"], correctAnswer: 0 },
            { id: 7, category: "Entertainment", question: "Who won the first season of 'American Idol'?", options: ["Kelly Clarkson", "Carrie Underwood", "Justin Guarini", "Clay Aiken"], correctAnswer: 0 },
            { id: 8, category: "Entertainment", question: "Which movie features a character named 'Forrest Gump'?", options: ["Forrest Gump", "Cast Away", "The Green Mile", "Saving Private Ryan"], correctAnswer: 0 },
            { id: 9, category: "Entertainment", question: "Who played the character of Katniss Everdeen in 'The Hunger Games'?", options: ["Jennifer Lawrence", "Emma Watson", "Kristen Stewart", "Shailene Woodley"], correctAnswer: 0 },
            { id: 10, category: "Entertainment", question: "What is the name of the fictional hobbit played by Elijah Wood in 'The Lord of the Rings'?", options: ["Frodo Baggins", "Samwise Gamgee", "Gimli", "Aragorn"], correctAnswer: 0 },
        ],
    },
    {
        id: 6,
        name: "Sports",
        questions: [
            { id: 1, category: "Sports", question: "Which country hosted the 2016 Summer Olympics?", options: ["Brazil", "China", "USA", "Australia"], correctAnswer: 0 },
            { id: 2, category: "Sports", question: "Who holds the record for the most goals scored in World Cup history?", options: ["Cristiano Ronaldo", "Lionel Messi", "Marta", "Miroslav Klose"], correctAnswer: 3 },
            { id: 3, category: "Sports", question: "Which sport is known as 'the king of sports'?", options: ["Basketball", "Soccer", "Cricket", "Tennis"], correctAnswer: 1 },
            { id: 4, category: "Sports", question: "Who won the FIFA World Cup in 2014?", options: ["Brazil", "Germany", "Argentina", "France"], correctAnswer: 1 },
            { id: 5, category: "Sports", question: "Which country won the most gold medals in the 2020 Summer Olympics?", options: ["USA", "China", "Russia", "Japan"], correctAnswer: 0 },
            { id: 6, category: "Sports", question: "In tennis, what is the term for a score of 40-40?", options: ["Deuce", "Advantage", "Set", "Match"], correctAnswer: 0 },
            { id: 7, category: "Sports", question: "Which NFL team has won the most Super Bowl titles?", options: ["Dallas Cowboys", "New England Patriots", "Pittsburgh Steelers", "San Francisco 49ers"], correctAnswer: 1 },
            { id: 8, category: "Sports", question: "Who holds the record for the fastest 100m sprint?", options: ["Usain Bolt", "Tyson Gay", "Asafa Powell", "Carl Lewis"], correctAnswer: 0 },
            { id: 9, category: "Sports", question: "Which sport is played on a court with a net and a shuttlecock?", options: ["Tennis", "Badminton", "Volleyball", "Table Tennis"], correctAnswer: 1 },
            { id: 10, category: "Sports", question: "Who won the 2021 Formula 1 World Championship?", options: ["Lewis Hamilton", "Sebastian Vettel", "Max Verstappen", "Daniel Ricciardo"], correctAnswer: 2 },
        ],
    },
    {
        id: 7,
        name: "Literature",
        questions: [
            { id: 1, category: "Literature", question: "Who wrote the play 'Romeo and Juliet'?", options: ["William Shakespeare", "Charles Dickens", "Jane Austen", "Oscar Wilde"], correctAnswer: 0 },
            { id: 2, category: "Literature", question: "What is the title of the first book in the Harry Potter series?", options: ["The Goblet of Fire", "The Half-Blood Prince", "The Philosopher's Stone", "The Prisoner of Azkaban"], correctAnswer: 2 },
            { id: 3, category: "Literature", question: "Which novel begins with the sentence 'Call me Ishmael'?", options: ["Moby-Dick", "Pride and Prejudice", "Great Expectations", "The Catcher in the Rye"], correctAnswer: 0 },
            { id: 4, category: "Literature", question: "Who is the author of '1984'?", options: ["George Orwell", "Aldous Huxley", "Ray Bradbury", "H.G. Wells"], correctAnswer: 0 },
            { id: 5, category: "Literature", question: "Which novel is the story of a young orphan girl named Anne Shirley?", options: ["Little Women", "Anne of Green Gables", "The Secret Garden", "The Adventures of Tom Sawyer"], correctAnswer: 1 },
            { id: 6, category: "Literature", question: "Who wrote the novel 'Pride and Prejudice'?", options: ["Charlotte Brontë", "Emily Dickinson", "Jane Austen", "Virginia Woolf"], correctAnswer: 2 },
            { id: 7, category: "Literature", question: "Which American author wrote 'The Great Gatsby'?", options: ["F. Scott Fitzgerald", "Ernest Hemingway", "Mark Twain", "John Steinbeck"], correctAnswer: 0 },
            { id: 8, category: "Literature", question: "Which Shakespeare play features the characters of Hamlet, Ophelia, and Claudius?", options: ["Macbeth", "Romeo and Juliet", "Hamlet", "King Lear"], correctAnswer: 2 },
            { id: 9, category: "Literature", question: "Who wrote 'The Lord of the Rings' trilogy?", options: ["J.K. Rowling", "C.S. Lewis", "J.R.R. Tolkien", "George R.R. Martin"], correctAnswer: 2 },
            { id: 10, category: "Literature", question: "In which country is the novel 'One Hundred Years of Solitude' set?", options: ["Mexico", "Colombia", "Argentina", "Brazil"], correctAnswer: 1 },
        ],
    },
    {
        id: 8,
        name: "Music",
        questions: [
            { id: 1, category: "Music", question: "Who is known as the 'King of Pop'?", options: ["Michael Jackson", "Elvis Presley", "Prince", "Madonna"], correctAnswer: 0 },
            { id: 2, category: "Music", question: "Which band released the album 'Abbey Road'?", options: ["The Beatles", "Pink Floyd", "The Rolling Stones", "Led Zeppelin"], correctAnswer: 0 },
            { id: 3, category: "Music", question: "What is the title of Adele's debut album?", options: ["25", "21", "19", "Hello"], correctAnswer: 2 },
            { id: 4, category: "Music", question: "Which famous composer wrote 'The Four Seasons'?", options: ["Ludwig van Beethoven", "Johann Sebastian Bach", "Wolfgang Amadeus Mozart", "Antonio Vivaldi"], correctAnswer: 3 },
            { id: 5, category: "Music", question: "Which artist sang 'Like a Virgin'?", options: ["Madonna", "Lady Gaga", "Beyoncé", "Britney Spears"], correctAnswer: 0 },
            { id: 6, category: "Music", question: "Which instrument is typically associated with jazz music?", options: ["Piano", "Drums", "Saxophone", "Trumpet"], correctAnswer: 2 },
            { id: 7, category: "Music", question: "Who is the lead singer of the band Coldplay?", options: ["Chris Martin", "Adam Levine", "Brandon Flowers", "James Hetfield"], correctAnswer: 0 },
            { id: 8, category: "Music", question: "Which city is home to the famous 'Hollywood Walk of Fame'?", options: ["New York", "London", "Los Angeles", "Nashville"], correctAnswer: 2 },
            { id: 9, category: "Music", question: "Which song did Whitney Houston famously cover in 1992?", options: ["I Will Always Love You", "Like a Prayer", "Respect", "Rolling in the Deep"], correctAnswer: 0 },
            { id: 10, category: "Music", question: "Which classical composer became deaf later in life?", options: ["Ludwig van Beethoven", "Johann Sebastian Bach", "Pyotr Ilyich Tchaikovsky", "Frédéric Chopin"], correctAnswer: 0 },
        ],
    },
    {
        id: 9,
        name: "Technology",
        questions: [
            { id: 1, category: "Technology", question: "Who is the co-founder of Microsoft?", options: ["Steve Jobs", "Bill Gates", "Mark Zuckerberg", "Larry Page"], correctAnswer: 1 },
            { id: 2, category: "Technology", question: "What does 'HTML' stand for?", options: ["HyperText Markup Language", "HighText Machine Language", "HyperTool Multi Language", "HyperText Marking Language"], correctAnswer: 0 },
            { id: 3, category: "Technology", question: "Which company developed the first smartphone?", options: ["Apple", "Nokia", "IBM", "Samsung"], correctAnswer: 2 },
            { id: 4, category: "Technology", question: "Which programming language is primarily used for iOS app development?", options: ["Java", "Swift", "Python", "Ruby"], correctAnswer: 1 },
            { id: 5, category: "Technology", question: "What is the name of Tesla's CEO?", options: ["Jeff Bezos", "Elon Musk", "Bill Gates", "Mark Zuckerberg"], correctAnswer: 1 },
            { id: 6, category: "Technology", question: "Which technology is used to create virtual reality experiences?", options: ["Augmented Reality", "Virtual Reality Headset", "Motion Sensing", "All of the above"], correctAnswer: 3 },
            { id: 7, category: "Technology", question: "Which company invented the first computer mouse?", options: ["Apple", "Microsoft", "Xerox", "IBM"], correctAnswer: 2 },
            { id: 8, category: "Technology", question: "What does 'CPU' stand for?", options: ["Central Processing Unit", "Computer Personal Unit", "Central Performance Unit", "Central Power Unit"], correctAnswer: 0 },
            { id: 9, category: "Technology", question: "What year was the World Wide Web first introduced?", options: ["1990", "1985", "2000", "1995"], correctAnswer: 0 },
            { id: 10, category: "Technology", question: "Which social media platform was founded by Mark Zuckerberg?", options: ["Instagram", "Twitter", "Snapchat", "Facebook"], correctAnswer: 3 },
        ],
    },
    {
        id: 10,
        name: "Movies",
        questions: [
            { id: 1, category: "Movies", question: "Who directed the movie 'Inception'?", options: ["Steven Spielberg", "Christopher Nolan", "James Cameron", "Martin Scorsese"], correctAnswer: 1 },
            { id: 2, category: "Movies", question: "Which movie won the Academy Award for Best Picture in 1994?", options: ["Forrest Gump", "Pulp Fiction", "The Shawshank Redemption", "The Lion King"], correctAnswer: 0 },
            { id: 3, category: "Movies", question: "What is the highest-grossing film of all time?", options: ["Titanic", "Avatar", "Avengers: Endgame", "Star Wars: The Force Awakens"], correctAnswer: 2 },
            { id: 4, category: "Movies", question: "Which actor played the role of Jack Dawson in 'Titanic'?", options: ["Leonardo DiCaprio", "Brad Pitt", "Johnny Depp", "Matt Damon"], correctAnswer: 0 },
            { id: 5, category: "Movies", question: "In which movie would you find the character 'Darth Vader'?", options: ["Star Wars", "The Matrix", "Lord of the Rings", "Jurassic Park"], correctAnswer: 0 },
            { id: 6, category: "Movies", question: "Which movie is known for the line 'Here's looking at you, kid'?", options: ["Casablanca", "Gone with the Wind", "The Godfather", "Citizen Kane"], correctAnswer: 0 },
            { id: 7, category: "Movies", question: "Which movie features the character 'The Joker' played by Heath Ledger?", options: ["The Dark Knight", "Batman Begins", "Justice League", "Suicide Squad"], correctAnswer: 0 },
            { id: 8, category: "Movies", question: "Which movie was the first to feature a Marvel superhero team-up?", options: ["Iron Man", "Thor", "The Avengers", "Captain America: The First Avenger"], correctAnswer: 2 },
            { id: 9, category: "Movies", question: "What is the name of the fictional African country in 'Black Panther'?", options: ["Zamunda", "Wakanda", "Elbonia", "Genovia"], correctAnswer: 1 },
            { id: 10, category: "Movies", question: "Who starred as the 'Terminator' in the 1984 film?", options: ["Arnold Schwarzenegger", "Sylvester Stallone", "Bruce Willis", "Jean-Claude Van Damme"], correctAnswer: 0 },
        ],
    },
    {
        id: 11,
        name: "Food & Drink",
        questions: [
            { id: 1, category: "Food & Drink", question: "What is the main ingredient in guacamole?", options: ["Tomato", "Avocado", "Onion", "Pepper"], correctAnswer: 1 },
            { id: 2, category: "Food & Drink", question: "Which country is famous for its sushi?", options: ["China", "Japan", "Thailand", "Korea"], correctAnswer: 1 },
            { id: 3, category: "Food & Drink", question: "Which fruit is known as the 'king of fruits'?", options: ["Mango", "Durian", "Pineapple", "Banana"], correctAnswer: 1 },
            { id: 4, category: "Food & Drink", question: "What type of food is 'Tempura'?", options: ["Fried", "Grilled", "Boiled", "Steamed"], correctAnswer: 0 },
            { id: 5, category: "Food & Drink", question: "Which Italian dish is made of thinly sliced raw meat, typically served as an appetizer?", options: ["Lasagna", "Carpaccio", "Risotto", "Pizza"], correctAnswer: 1 },
            { id: 6, category: "Food & Drink", question: "What is the main ingredient in hummus?", options: ["Chickpeas", "Lentils", "Tomatoes", "Potatoes"], correctAnswer: 0 },
            { id: 7, category: "Food & Drink", question: "Which alcoholic beverage is made from fermented grapes?", options: ["Whiskey", "Vodka", "Wine", "Beer"], correctAnswer: 2 },
            { id: 8, category: "Food & Drink", question: "Which dish is traditionally made with chicken, rice, and vegetables, originating from Spain?", options: ["Paella", "Ratatouille", "Sushi", "Curry"], correctAnswer: 0 },
            { id: 9, category: "Food & Drink", question: "What is the name of the famous French dish made with beef, carrots, and red wine?", options: ["Beef Wellington", "Coq au Vin", "Boeuf Bourguignon", "Escargot"], correctAnswer: 2 },
            { id: 10, category: "Food & Drink", question: "Which popular drink is made by fermenting tea with sugar and bacteria?", options: ["Kombucha", "Lemonade", "Coffee", "Iced Tea"], correctAnswer: 0 },
        ],
    },
    {
        id: 12,
        name: "Animals",
        questions: [
            { id: 1, category: "Animals", question: "What is the largest mammal on Earth?", options: ["Elephant", "Blue Whale", "Giraffe", "Shark"], correctAnswer: 1 },
            { id: 2, category: "Animals", question: "Which bird is known for its ability to mimic human speech?", options: ["Parrot", "Eagle", "Sparrow", "Peacock"], correctAnswer: 0 },
            { id: 3, category: "Animals", question: "What is the fastest land animal?", options: ["Cheetah", "Lion", "Gazelle", "Tiger"], correctAnswer: 0 },
            { id: 4, category: "Animals", question: "Which animal is known as the 'King of the Jungle'?", options: ["Elephant", "Lion", "Tiger", "Gorilla"], correctAnswer: 1 },
            { id: 5, category: "Animals", question: "Which sea creature has three hearts?", options: ["Shark", "Octopus", "Whale", "Dolphin"], correctAnswer: 1 },
            { id: 6, category: "Animals", question: "What is the largest species of bear?", options: ["Polar Bear", "Grizzly Bear", "Panda Bear", "Koala Bear"], correctAnswer: 0 },
            { id: 7, category: "Animals", question: "What is the only mammal capable of flight?", options: ["Bat", "Squirrel", "Eagle", "Penguin"], correctAnswer: 0 },
            { id: 8, category: "Animals", question: "Which animal is known for changing its color to blend into its environment?", options: ["Chameleon", "Snake", "Frog", "Lizard"], correctAnswer: 0 },
            { id: 9, category: "Animals", question: "What is the largest species of cat?", options: ["Lion", "Tiger", "Jaguar", "Cheetah"], correctAnswer: 1 },
            { id: 10, category: "Animals", question: "Which animal is known for its distinctive black and white stripes?", options: ["Zebra", "Horse", "Donkey", "Giraffe"], correctAnswer: 0 },
        ],
    },
    {
        id: 13,
        name: "Mythology",
        questions: [
            { id: 1, category: "Mythology", question: "Who is the Greek god of thunder?", options: ["Zeus", "Hades", "Poseidon", "Apollo"], correctAnswer: 0 },
            { id: 2, category: "Mythology", question: "In Norse mythology, who is the god of mischief?", options: ["Odin", "Thor", "Loki", "Freya"], correctAnswer: 2 },
            { id: 3, category: "Mythology", question: "Which Egyptian goddess is associated with the moon and magic?", options: ["Isis", "Hathor", "Bastet", "Selene"], correctAnswer: 0 },
            { id: 4, category: "Mythology", question: "Who was the Greek hero who performed twelve labors?", options: ["Perseus", "Heracles", "Achilles", "Jason"], correctAnswer: 1 },
            { id: 5, category: "Mythology", question: "In Roman mythology, who is the goddess of love?", options: ["Juno", "Minerva", "Venus", "Diana"], correctAnswer: 2 },
            { id: 6, category: "Mythology", question: "Which Hindu god is known as the god of destruction?", options: ["Vishnu", "Shiva", "Brahma", "Indra"], correctAnswer: 1 },
            { id: 7, category: "Mythology", question: "Who is the Norse god associated with thunder and storms?", options: ["Loki", "Freya", "Thor", "Odin"], correctAnswer: 2 },
            { id: 8, category: "Mythology", question: "In Greek mythology, who was the Titan who held up the sky?", options: ["Prometheus", "Atlas", "Cronus", "Uranus"], correctAnswer: 1 },
            { id: 9, category: "Mythology", question: "Which ancient civilization worshipped the god Ra?", options: ["Greek", "Roman", "Egyptian", "Mayan"], correctAnswer: 2 },
            { id: 10, category: "Mythology", question: "In Roman mythology, who was the god of war?", options: ["Mars", "Jupiter", "Apollo", "Neptune"], correctAnswer: 0 },
        ],
    },
    {
        id: 14,
        name: "Art",
        questions: [
            { id: 1, category: "Art", question: "Who painted the Mona Lisa?", options: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Michelangelo"], correctAnswer: 1 },
            { id: 2, category: "Art", question: "Who created the famous sculpture 'David'?", options: ["Donatello", "Leonardo da Vinci", "Michelangelo", "Raphael"], correctAnswer: 2 },
            { id: 3, category: "Art", question: "Which artist is known for the painting 'The Starry Night'?", options: ["Claude Monet", "Vincent van Gogh", "Pablo Picasso", "Andy Warhol"], correctAnswer: 1 },
            { id: 4, category: "Art", question: "Which famous artist is known for his work 'The Persistence of Memory'?", options: ["Salvador Dalí", "Pablo Picasso", "Vincent van Gogh", "Jackson Pollock"], correctAnswer: 0 },
            { id: 5, category: "Art", question: "Who painted the Sistine Chapel ceiling?", options: ["Raphael", "Leonardo da Vinci", "Michelangelo", "Donatello"], correctAnswer: 2 },
            { id: 6, category: "Art", question: "Which artist is known for the work 'Guernica'?", options: ["Salvador Dalí", "Pablo Picasso", "Claude Monet", "Edvard Munch"], correctAnswer: 1 },
            { id: 7, category: "Art", question: "Which art movement is Pablo Picasso known for?", options: ["Cubism", "Surrealism", "Impressionism", "Realism"], correctAnswer: 0 },
            { id: 8, category: "Art", question: "What is the title of Leonardo da Vinci's famous notebook?", options: ["The Last Supper", "The Codex Leicester", "Vitruvian Man", "Mona Lisa"], correctAnswer: 1 },
            { id: 9, category: "Art", question: "Which artist is famous for the painting 'Water Lilies'?", options: ["Claude Monet", "Salvador Dalí", "Edvard Munch", "Henri Matisse"], correctAnswer: 0 },
            { id: 10, category: "Art", question: "Which famous painting by Edvard Munch is often interpreted as a representation of anxiety?", options: ["The Scream", "The Persistence of Memory", "Girl with a Pearl Earring", "The Night Watch"], correctAnswer: 0 },
        ],
    },
    {
        id: 15,
        name: "World Leaders",
        questions: [
            { id: 1, category: "World Leaders", question: "Who was the first president of the United States?", options: ["George Washington", "Thomas Jefferson", "Abraham Lincoln", "John Adams"], correctAnswer: 0 },
            { id: 2, category: "World Leaders", question: "Who was the first female prime minister of the United Kingdom?", options: ["Margaret Thatcher", "Elizabeth II", "Theresa May", "Angela Merkel"], correctAnswer: 0 },
            { id: 3, category: "World Leaders", question: "Who was the leader of the Soviet Union during World War II?", options: ["Joseph Stalin", "Leonid Brezhnev", "Mikhail Gorbachev", "Nikita Khrushchev"], correctAnswer: 0 },
            { id: 4, category: "World Leaders", question: "Who was the president of South Africa during the end of apartheid?", options: ["Nelson Mandela", "Thabo Mbeki", "Jacob Zuma", "F.W. de Klerk"], correctAnswer: 0 },
            { id: 5, category: "World Leaders", question: "Who was the longest-serving monarch in British history?", options: ["Queen Elizabeth II", "Queen Victoria", "King George III", "King Henry VIII"], correctAnswer: 0 },
            { id: 6, category: "World Leaders", question: "Who was the first emperor of China?", options: ["Qin Shi Huang", "Wang Mang", "Liu Bang", "Han Wudi"], correctAnswer: 0 },
            { id: 7, category: "World Leaders", question: "Who was the leader of Nazi Germany during World War II?", options: ["Adolf Hitler", "Heinrich Himmler", "Joseph Goebbels", "Hermann Göring"], correctAnswer: 0 },
            { id: 8, category: "World Leaders", question: "Who was the first woman to serve as the prime minister of India?", options: ["Indira Gandhi", "Sarojini Naidu", "Pratibha Patil", "Sonia Gandhi"], correctAnswer: 0 },
            { id: 9, category: "World Leaders", question: "Who was the president of the United States during the Cuban Missile Crisis?", options: ["John F. Kennedy", "Dwight D. Eisenhower", "Lyndon B. Johnson", "Richard Nixon"], correctAnswer: 0 },
            { id: 10, category: "World Leaders", question: "Who was the first president of modern Turkey?", options: ["Mustafa Kemal Atatürk", "Ismet Inönü", "Turgut Özal", "Recep Tayyip Erdoğan"], correctAnswer: 0 },
        ],
    },
    {
        id: 16,
        name: "Space",
        questions: [
            { id: 1, category: "Space", question: "What is the largest planet in our solar system?", options: ["Earth", "Jupiter", "Saturn", "Mars"], correctAnswer: 1 },
            { id: 2, category: "Space", question: "What is the closest star to Earth?", options: ["The Sun", "Alpha Centauri", "Proxima Centauri", "Sirius"], correctAnswer: 0 },
            { id: 3, category: "Space", question: "What was the first manned mission to land on the Moon?", options: ["Apollo 11", "Apollo 13", "Gemini 8", "Mercury 7"], correctAnswer: 0 },
            { id: 4, category: "Space", question: "Which planet is known as the Red Planet?", options: ["Mars", "Venus", "Earth", "Saturn"], correctAnswer: 0 },
            { id: 5, category: "Space", question: "Which spacecraft was the first to leave our solar system?", options: ["Voyager 1", "Voyager 2", "Parker Solar Probe", "New Horizons"], correctAnswer: 0 },
            { id: 6, category: "Space", question: "What is the name of the first human to travel into space?", options: ["Neil Armstrong", "Yuri Gagarin", "Buzz Aldrin", "Alan Shepard"], correctAnswer: 1 },
            { id: 7, category: "Space", question: "Which planet has the most moons?", options: ["Earth", "Mars", "Saturn", "Jupiter"], correctAnswer: 3 },
            { id: 8, category: "Space", question: "What is the name of our galaxy?", options: ["Andromeda", "Milky Way", "Whirlpool", "Sombrero"], correctAnswer: 1 },
            { id: 9, category: "Space", question: "What is the term for the explosion of a star?", options: ["Solar flare", "Nova", "Supernova", "Black hole"], correctAnswer: 2 },
            { id: 10, category: "Space", question: "Which planet is known for having rings?", options: ["Mars", "Jupiter", "Saturn", "Uranus"], correctAnswer: 2 },
        ],
    },
    {
        id: 17,
        name: "Nature",
        questions: [
            { id: 1, category: "Nature", question: "What is the largest mammal on Earth?", options: ["Elephant", "Blue Whale", "Giraffe", "Shark"], correctAnswer: 1 },
            { id: 2, category: "Nature", question: "Which animal is known as the King of the Jungle?", options: ["Tiger", "Lion", "Elephant", "Bear"], correctAnswer: 1 },
            { id: 3, category: "Nature", question: "What is the process by which plants make their own food?", options: ["Respiration", "Photosynthesis", "Fermentation", "Pollination"], correctAnswer: 1 },
            { id: 4, category: "Nature", question: "Which bird is known for its ability to mimic human speech?", options: ["Parrot", "Sparrow", "Eagle", "Penguin"], correctAnswer: 0 },
            { id: 5, category: "Nature", question: "What is the tallest tree species in the world?", options: ["Sequoia", "Redwood", "Oak", "Pine"], correctAnswer: 1 },
            { id: 6, category: "Nature", question: "Which is the smallest mammal in the world?", options: ["Bat", "Shrew", "Mouse", "Hedgehog"], correctAnswer: 1 },
            { id: 7, category: "Nature", question: "What is the natural habitat of a polar bear?", options: ["Desert", "Savanna", "Arctic", "Rainforest"], correctAnswer: 2 },
            { id: 8, category: "Nature", question: "Which plant is known for producing the world's largest flower?", options: ["Titan Arum", "Rose", "Tulip", "Daisy"], correctAnswer: 0 },
            { id: 9, category: "Nature", question: "What is the primary gas that plants use for photosynthesis?", options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], correctAnswer: 1 },
            { id: 10, category: "Nature", question: "What is the fastest land animal?", options: ["Cheetah", "Lion", "Antelope", "Tiger"], correctAnswer: 0 },
        ],
    },
    {
        id: 18,
        name: "Health",
        questions: [
            { id: 1, category: "Health", question: "What is the recommended daily intake of water for adults?", options: ["1 liter", "2 liters", "3 liters", "5 liters"], correctAnswer: 1 },
            { id: 2, category: "Health", question: "What vitamin is known as the sunshine vitamin?", options: ["Vitamin A", "Vitamin B12", "Vitamin C", "Vitamin D"], correctAnswer: 3 },
            { id: 3, category: "Health", question: "Which organ is primarily responsible for detoxifying the body?", options: ["Liver", "Kidney", "Heart", "Lungs"], correctAnswer: 0 },
            { id: 4, category: "Health", question: "What is the normal body temperature for a healthy adult?", options: ["36°C", "37°C", "38°C", "39°C"], correctAnswer: 1 },
            { id: 5, category: "Health", question: "Which disease is caused by a deficiency of insulin?", options: ["Hypertension", "Diabetes", "Asthma", "Arthritis"], correctAnswer: 1 },
            { id: 6, category: "Health", question: "Which of these is a common symptom of dehydration?", options: ["Excessive thirst", "Constant hunger", "Severe fatigue", "All of the above"], correctAnswer: 0 },
            { id: 7, category: "Health", question: "Which nutrient is vital for bone health?", options: ["Vitamin C", "Calcium", "Iron", "Magnesium"], correctAnswer: 1 },
            { id: 8, category: "Health", question: "Which of these diseases is transmitted by mosquitoes?", options: ["Tuberculosis", "Malaria", "Cholera", "HIV"], correctAnswer: 1 },
            { id: 9, category: "Health", question: "What is the main cause of heart disease?", options: ["Poor diet", "Genetics", "Exercise", "Stress"], correctAnswer: 0 },
            { id: 10, category: "Health", question: "How many hours of sleep do adults typically need per night?", options: ["5-6 hours", "7-8 hours", "9-10 hours", "10-12 hours"], correctAnswer: 1 },
        ]
    },
    {
        id: 19,
        name: "Comics",
        questions: [
            { id: 1, category: "Comics", question: "Who created the superhero character 'Spider-Man'?", options: ["Stan Lee", "Jack Kirby", "Steve Ditko", "Bob Kane"], correctAnswer: 0 },
            { id: 2, category: "Comics", question: "Which comic book company publishes 'Batman'?", options: ["Marvel", "DC Comics", "Dark Horse", "Image Comics"], correctAnswer: 1 },
            { id: 3, category: "Comics", question: "Which superhero is known as the 'Man of Steel'?", options: ["Iron Man", "Thor", "Superman", "Hulk"], correctAnswer: 2 },
            { id: 4, category: "Comics", question: "What is the name of Wonder Woman's homeland?", options: ["Themyscira", "Asgard", "Krypton", "Wakanda"], correctAnswer: 0 },
            { id: 5, category: "Comics", question: "Who is the arch-nemesis of the Flash?", options: ["Green Goblin", "Joker", "Reverse Flash", "Lex Luthor"], correctAnswer: 2 },
            { id: 6, category: "Comics", question: "Which superhero has the power of 'ring constructs'?", options: ["Green Lantern", "Iron Man", "Hawkeye", "Doctor Strange"], correctAnswer: 0 },
            { id: 7, category: "Comics", question: "Which Marvel hero was once a scientist named Bruce Banner?", options: ["Hawkeye", "Iron Man", "The Hulk", "Captain America"], correctAnswer: 2 },
            { id: 8, category: "Comics", question: "Who is the leader of the X-Men?", options: ["Storm", "Professor X", "Cyclops", "Wolverine"], correctAnswer: 1 },
            { id: 9, category: "Comics", question: "Which superhero team was formed to stop the threat of Thanos?", options: ["The Avengers", "Justice League", "Fantastic Four", "The X-Men"], correctAnswer: 0 },
            { id: 10, category: "Comics", question: "What is the real name of the superhero Black Panther?", options: ["T'Challa", "Peter Parker", "Bruce Wayne", "Clark Kent"], correctAnswer: 0 },
        ]
    },
    {
        id: 20,
        name: "Video Games",
        questions: [
            { id: 1, category: "Video Games", question: "In which arcade game did the character 'Mario' first appear?", options: ["Super Mario Bros.", "Donkey Kong", "Space Invaders", "Popeye"], correctAnswer: 1 },
            { id: 2, category: "Video Games", question: "Which video game holds the record for the most copies sold worldwide across all platforms?", options: ["Minecraft", "Grand Theft Auto V", "The Legend of Zelda: Breath of the Wild", "Tetris"], correctAnswer: 0 },
            { id: 3, category: "Video Games", question: "What year was the original 'Pokémon Red' and 'Blue' first released?", options: ["1995", "1996", "1997", "1998"], correctAnswer: 1 },
            { id: 4, category: "Video Games", question: "In 'Fortnite', which feature was introduced in Chapter 2 that significantly altered gameplay?", options: ["Map redesign", "Building mechanics", "Cross-platform play", "Water physics"], correctAnswer: 0 },
            { id: 5, category: "Video Games", question: "Which was the first console to feature motion-sensing controllers?", options: ["PlayStation Move", "Nintendo Wii", "Xbox Kinect", "Nintendo Switch"], correctAnswer: 1 },
            { id: 6, category: "Video Games", question: "Which game series introduced the character 'Luigi' as a primary protagonist in its own game?", options: ["Super Mario Bros.", "Luigi's Mansion", "Mario Kart", "Super Paper Mario"], correctAnswer: 1 },
            { id: 7, category: "Video Games", question: "In which game did the 'Battle Royale' genre originate?", options: ["Fortnite", "PUBG", "H1Z1", "The Hunger Games: The Game"], correctAnswer: 2 },
            { id: 8, category: "Video Games", question: "What is the main weapon used by the protagonist 'Link' in The Legend of Zelda series?", options: ["Master Sword", "Hookshot", "Bombs", "Bow and Arrow"], correctAnswer: 0 },
            { id: 9, category: "Video Games", question: "What was the original name of the protagonist in the 'Metroid' series before it was revealed to be female?", options: ["Adam", "Samus", "Ridley", "James"], correctAnswer: 1 },
            { id: 10, category: "Video Games", question: "In the original 'Pac-Man' arcade game, how many ghosts are there, and what are their names?", options: ["3 ghosts: Blinky, Pinky, Clyde", "4 ghosts: Blinky, Pinky, Inky, Clyde", "5 ghosts: Blinky, Pinky, Inky, Clyde, Sue", "4 ghosts: Blinky, Inky, Pinky, and Speedy"], correctAnswer: 1 },
        ]
    },
    {
        id: 21,
        name: "Social Sciences",
        questions: [
            { id: 1, category: "Social Sciences", question: "What is the study of human societies and cultures called?", options: ["Psychology", "Sociology", "Anthropology", "Philosophy"], correctAnswer: 2 },
            { id: 2, category: "Social Sciences", question: "Which concept involves the distribution of wealth among individuals in a society?", options: ["Income inequality", "Globalization", "Democracy", "Capitalism"], correctAnswer: 0 },
            { id: 3, category: "Social Sciences", question: "What is the term for the practice of studying human behavior?", options: ["Ethnography", "Psychology", "Economics", "Political Science"], correctAnswer: 1 },
            { id: 4, category: "Social Sciences", question: "Which branch of social science studies the production, distribution, and consumption of goods and services?", options: ["Economics", "Sociology", "History", "Psychology"], correctAnswer: 0 },
            { id: 5, category: "Social Sciences", question: "What system of government allows citizens to vote for their leaders?", options: ["Monarchy", "Oligarchy", "Democracy", "Theocracy"], correctAnswer: 2 },
            { id: 6, category: "Social Sciences", question: "Which theory suggests that individuals' behavior is shaped by their social interactions?", options: ["Social Darwinism", "Behaviorism", "Symbolic Interactionism", "Structuralism"], correctAnswer: 2 },
            { id: 7, category: "Social Sciences", question: "What term is used for the ability of people to participate in the political and social decisions of a community?", options: ["Social mobility", "Civic engagement", "Cultural diffusion", "Political activism"], correctAnswer: 1 },
            { id: 8, category: "Social Sciences", question: "Which philosopher is known for his theory of the 'social contract'?", options: ["Karl Marx", "John Locke", "Thomas Hobbes", "Jean-Jacques Rousseau"], correctAnswer: 3 },
            { id: 9, category: "Social Sciences", question: "Which field focuses on the study of law, legal systems, and justice?", options: ["Law", "Sociology", "Political Science", "Criminology"], correctAnswer: 0 },
            { id: 10, category: "Social Sciences", question: "Which is the study of how human societies change over time?", options: ["Anthropology", "Sociology", "Political Science", "History"], correctAnswer: 3 },
        ]
    },
    {
        id: 22,
        name: "Mathematics",
        questions: [
            { id: 1, category: "Mathematics", question: "What is the value of pi (π) approximately?", options: ["3.1415", "2.7182", "1.6180", "3.0000"], correctAnswer: 0 },
            { id: 2, category: "Mathematics", question: "What is the square root of 64?", options: ["6", "8", "10", "12"], correctAnswer: 1 },
            { id: 3, category: "Mathematics", question: "Which is the sum of the interior angles of a triangle?", options: ["180°", "90°", "360°", "270°"], correctAnswer: 0 },
            { id: 4, category: "Mathematics", question: "What is the derivative of x²?", options: ["2x", "x", "x²", "1"], correctAnswer: 0 },
            { id: 5, category: "Mathematics", question: "What is the result of 7 × 8?", options: ["56", "48", "64", "72"], correctAnswer: 0 },
            { id: 6, category: "Mathematics", question: "Which is the next prime number after 7?", options: ["9", "11", "13", "15"], correctAnswer: 1 },
            { id: 7, category: "Mathematics", question: "What is the value of 2³?", options: ["4", "6", "8", "10"], correctAnswer: 2 },
            { id: 8, category: "Mathematics", question: "What is the area of a circle with a radius of 5 units?", options: ["25π", "10π", "15π", "20π"], correctAnswer: 0 },
            { id: 9, category: "Mathematics", question: "What is the formula for the area of a rectangle?", options: ["length × width", "width × height", "length + width", "length²"], correctAnswer: 0 },
            { id: 10, category: "Mathematics", question: "What is the value of 100 ÷ 4?", options: ["25", "50", "75", "20"], correctAnswer: 0 },
        ]
    },
    {
        id: 23,
        name: "Random",
        questions: [
            { id: 1, category: "Random", question: "Which planet is known as the Red Planet?", options: ["Earth", "Mars", "Venus", "Saturn"], correctAnswer: 1 },
            { id: 2, category: "Random", question: "Which element is represented by the symbol 'O'?", options: ["Oxygen", "Osmium", "Ozone", "Oganesson"], correctAnswer: 0 },
            { id: 3, category: "Random", question: "Who wrote the novel '1984'?", options: ["George Orwell", "J.K. Rowling", "Harper Lee", "Ernest Hemingway"], correctAnswer: 0 },
            { id: 4, category: "Random", question: "What is the largest country by land area?", options: ["USA", "Russia", "China", "India"], correctAnswer: 1 },
            { id: 5, category: "Random", question: "Which animal is known as the 'King of the Jungle'?", options: ["Tiger", "Lion", "Elephant", "Giraffe"], correctAnswer: 1 },
            { id: 6, category: "Random", question: "What is the tallest mountain in the world?", options: ["Mount Everest", "K2", "Mount Kilimanjaro", "Mount Fuji"], correctAnswer: 0 },
            { id: 7, category: "Random", question: "Which of these is the symbol for gold?", options: ["Ag", "Au", "Fe", "Cu"], correctAnswer: 1 },
            { id: 8, category: "Random", question: "What is the largest ocean on Earth?", options: ["Atlantic", "Indian", "Arctic", "Pacific"], correctAnswer: 3 },
            { id: 9, category: "Random", question: "Which country is famous for the Eiffel Tower?", options: ["Italy", "USA", "France", "Germany"], correctAnswer: 2 },
            { id: 10, category: "Random", question: "In which city can you find the Colosseum?", options: ["Rome", "Paris", "Athens", "Berlin"], correctAnswer: 0 },
        ]
    }
];
